_wandb:
    value:
        cli_version: 0.23.1
        e:
            vyu89qi0pupbdqq0spwss9q59cu8y895:
                apple:
                    ecpuCores: 6
                    gpuCores: 18
                    memoryGb: 36
                    name: Apple M3 Pro
                    pcpuCores: 6
                    ramTotalBytes: "38654705664"
                    swapTotalBytes: "2147483648"
                codePath: monitor_pool_usage.py
                codePathLocal: monitor_pool_usage.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "739086831616"
                email: alexandre.drouin1@gmail.com
                executable: /Users/alexandre.drouin/.pyenv/versions/workarena-new-dispatch/bin/python
                git:
                    commit: 6d4194fcfe6bcd9dbfc55e88446ed367fa13c463
                    remote: https://github.com/ServiceNow/workarena
                host: MACKV69YQ3QPP
                memory:
                    total: "38654705664"
                os: macOS-15.7.2-arm64-arm-64bit
                program: /Users/alexandre.drouin/dev/git/workarena-new-dispatch/monitor_pool_usage.py
                python: CPython 3.12.7
                root: /Users/alexandre.drouin/dev/git/workarena-new-dispatch
                startedAt: "2025-12-08T06:59:35.195261Z"
                writerId: vyu89qi0pupbdqq0spwss9q59cu8y895
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 49
            "2":
                - 49
            "3":
                - 2
                - 14
                - 16
            "4": 3.12.7
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
date:
    value: null
hours:
    value: 24
